const $ = id => document.getElementById(id);
const ui = {connection:$('connectionText').parentElement,connectionText:$('connectionText'),state:$('stateText'),messages:$('messages'),empty:$('emptyState'),mic:$('micButton'),micText:$('micText'),voice:$('voiceSelect'),model:$('modelSelect'),asr:$('asrSelect'),tts:$('ttsSelect'),size:$('ttsSizeSelect'),engineNote:$('engineNote'),prompt:$('promptInput'),save:$('saveSettings'),result:$('saveResult'),asrMetric:$('asrMetric'),llmMetric:$('llmMetric'),input:$('textInput')};
let lastEvent=0, enabled=true, options=null, lastAssistant=null;

async function api(path, init={}){const r=await fetch(path,init);const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function fill(select,items){select.innerHTML='';items.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name;select.appendChild(o)})}
function updateSizes(){const engine=options.tts_engines.find(x=>x.id===ui.tts.value);const sizes=engine?.sizes||[];fill(ui.size,sizes.map(x=>({id:x,name:x})));ui.size.disabled=!sizes.length;if(!sizes.length){const o=document.createElement('option');o.textContent='固定';ui.size.appendChild(o)}ui.engineNote.textContent=ui.tts.value==='luxtts'?'低延迟模式：实测约 0.5 秒，中文速度优先。':'中文质量模式：声线更稳，但当前显卡实测约 9 秒。'}
async function loadOptions(){options=await api('/options');fill(ui.voice,options.profiles);fill(ui.model,options.ollama_models);fill(ui.asr,options.asr_models);fill(ui.tts,options.tts_engines);const c=options.current;ui.voice.value=c.voice_profile_id;ui.model.value=c.ollama_model;ui.asr.value=c.asr_model;ui.tts.value=c.tts_engine;ui.prompt.value=c.system_prompt||'';updateSizes();if(!ui.size.disabled)ui.size.value=c.tts_model_size}
function setConnection(ok,text){ui.connection.className='connection '+(ok?'online':'error');ui.connectionText.textContent=text}
function renderState(s){const map={listening:'正在聆听',hearing:'听到了，请继续说…',transcribing:'正在识别语音…',thinking:'正在生成回答…',speaking:'正在播放语音…',warming:'正在暖机…',paused:'语音已暂停',error:'服务异常'};ui.state.textContent=map[s]||s;ui.mic.classList.toggle('active',enabled);ui.micText.textContent=enabled?'暂停聆听':'继续聆听'}
function message(role,text,partial=false){if(ui.empty)ui.empty.remove();if(role==='assistant'&&partial&&lastAssistant){lastAssistant.querySelector('.bubble').firstChild.textContent=text;return}const row=document.createElement('div');row.className=`message ${role}`;const bubble=document.createElement('div');bubble.className='bubble';bubble.append(document.createTextNode(text));row.appendChild(bubble);ui.messages.appendChild(row);if(role==='assistant')lastAssistant=row;ui.messages.scrollTop=ui.messages.scrollHeight}
function consume(e){lastEvent=Math.max(lastEvent,e.id||0);if(e.state)renderState(e.state);if(e.type==='user'){lastAssistant=null;message('user',e.text);ui.asrMetric.textContent=e.elapsed_ms?`${e.elapsed_ms} ms`:'—'}if(e.type==='assistant_partial')message('assistant',e.text,true);if(e.type==='assistant'){message('assistant',e.text,true);ui.llmMetric.textContent=e.elapsed_ms?`${e.elapsed_ms} ms`:'—'}if(e.type==='error'){ui.result.className='save-result error';ui.result.textContent=e.detail||'语音服务异常'}if(e.type==='settings')ui.result.textContent=e.text}
async function poll(){try{const h=await api('/health');enabled=h.enabled;renderState(h.state);setConnection(h.ok,'本地服务在线');const data=await api(`/events?after=${lastEvent}`);data.events.forEach(consume)}catch(e){setConnection(false,'连接已断开');ui.state.textContent=e.message}finally{setTimeout(poll,220)}}
ui.tts.addEventListener('change',updateSizes);
ui.mic.addEventListener('click',async()=>{try{enabled=!enabled;const h=await api('/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});renderState(h.state)}catch(e){ui.result.textContent=e.message}});
ui.save.addEventListener('click',async()=>{ui.save.disabled=true;ui.result.className='save-result';ui.result.textContent='保存中，模型正在暖机…';try{await api('/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voice_profile_id:ui.voice.value,ollama_model:ui.model.value,asr_model:ui.asr.value,tts_engine:ui.tts.value,tts_model_size:ui.size.disabled?'0.6B':ui.size.value,system_prompt:ui.prompt.value})});ui.result.textContent='已保存，暖机完成后自动恢复聆听。'}catch(e){ui.result.className='save-result error';ui.result.textContent=e.message}finally{ui.save.disabled=false}});
$('textForm').addEventListener('submit',async e=>{e.preventDefault();const text=ui.input.value.trim();if(!text)return;try{await api('/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});message('user',text);ui.input.value=''}catch(err){ui.result.className='save-result error';ui.result.textContent=err.message}});
(async()=>{try{await loadOptions();setConnection(true,'本地服务在线')}catch(e){setConnection(false,'配置读取失败');ui.result.textContent=e.message}poll()})();
